title:  "Naujienos"
tagline: "Meškų žemėje"
description:
author:
  name: "Meškų žemė"
  twitter: meskuzeme

google-ID: "UA-106407565-1"

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'meskuzeme'

menu:
- {name: 'Parodos', file: 'facts.html'}
- {name: 'Veislyno gyvenimas', file: 'resources.html'}
- {name: 'Mūsų kelionės', file: 'sample-posts.html'}
- {name: 'Šuniukai', file: 'suniukai.html'}
- {name: 'Įdomi informacija, file: 'about.html'}
- {name: 'Contact', file: 'contact.html'}

social:
- {icon: 'twitter', link: 'https://twitter.com/paululele'}
- {icon: 'facebook', link: 'https://www.facebook.com/Le.Paul.94'}
- {icon: 'instagram', link: 'https://instagram.com/paululele'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/lenpaul'}
- {icon: 'envelope', link: 'mailto:l.nguyen.paul@gmail.com'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
